include $(PWD)/deb_rules

CFLAGS	:= `sdl-config  --static-libs --cflags --libs` -m32 -O3 -DCPP_MEMORY -Wall -I/usr/local/include -I$(PWD)/../sources -D__LINUX_ALSA__ -D__LINUX_ALSASEQ__ -D_DEBUG
LIBS   :=  -O3 -L/local/lib -Wl,-rpath,/usr/lib -ljack -lpthread -lSDL -lasound

#For debugging
#CFLAGS	:= -g -m32 -DCPP_MEMORY -Wall -I/usr/local/include -I$(PWD)/../sources -D__LINUX_ALSA__ -D__LINUX_ALSASEQ__
#LIBS	:=  -g -L/local/lib -Wl,-rpath,/usr/local/lib -lasound -lSDL -lSDL_image -lSDL_mixer -lSDLmain -ljack -lpthread

CXXFLAGS:= $(CFLAGS)
EXTENSION:= deb-exe
