DEVKIT=/opt/arm-buildroot-linux-musleabi_sdk-buildroot

TARGET = lgpt.elf

TOOLPATH=$(DEVKIT)/usr/bin
PREFIX		:=	arm-linux-
SDL_BASE = $(DEVKIT)/arm-buildroot-linux-musleabi/sysroot/usr/bin/

include $(PWD)/bittboy_rules

DEFINES = -DHAVE_STDINT_H -DVERSION_BITTBOY
INCLUDES = -Iinclude `$(SDL_BASE)sdl-config --cflags --libs`
OPT_FLAGS  = -Ofast -fdata-sections -fdata-sections -fno-common -fno-PIC -flto

CFLAGS	:=	$(DEFINES) $(INCLUDES) $(OPT_FLAGS)  -O3 -Wall -DPLATFORM_DINGOO -I$(PWD)/../sources -DCPP_MEMORY -DRS97
CXXFLAGS:=	$(CFLAGS) -std=gnu++11

EXTENSION:= elf

LIBS	:=  -lSDL -lasound -lpthread 
LIBDIRS	:=	$(DEKVIT)/usr/lib
