DEVKIT = /opt/miyoomini-toolchain/
CROSS_COMPILE=$(DEVKIT)bin/arm-linux-gnueabihf-
# CROSS_COMPILE=$(DEVKIT)bin/arm-buildroot-linux-musleabi-

CC = $(CROSS_COMPILE)gcc
CXX = $(CROSS_COMPILE)g++
SYSROOT     := $(shell $(CROSS_COMPILE)gcc --print-sysroot)
SDL_CFLAGS  := $(shell $(SYSROOT)/usr/bin/sdl-config --cflags)
SDL_LIBS    := $(shell $(SYSROOT)/usr/bin/sdl-config --libs)

DEFINES = -DHAVE_STDINT_H -DVERSION_BITTBOY
INCLUDES = -Iinclude $(SDL_CFLAGS)
OPT_FLAGS  = -Ofast -fdata-sections -fdata-sections -fno-common -fno-PIC -flto 

TARGET = lgpt.elf

TOOLPATH=$(DEVKIT)/usr/bin
PREFIX		:=	arm-linux-gnueabihf-

include $(PWD)/miyoo_rules

CFLAGS	:=	$(DEFINES) $(INCLUDES) -O3 -D_NDEBUG -D_NO_JACK_ -Wall -DPLATFORM_DINGOO -I$(PWD)/../sources -D__LINUX_ALSA__  -DCPP_MEMORY $(SDL_CFLAGS) $(SDL_LIBS) -DRS97 
CXXFLAGS:=	$(CFLAGS) -std=gnu++03 
#LDFLAGS = -Wl,--start-group -lSDL -lSDL_image -lpng -ljpeg -lSDL_mixer -lfreetype -lSDL_ttf -logg -lvorbisidec -lmikmod -lmodplug -lm -pthread -lz -lstdc++ $(EXTRA_LDFLAGS) -Wl,--end-group

EXTENSION:= elf

LIBS	:=  -lSDL -lSDL_mixer -lasound -lpthread 
LIBDIRS	:=	$(DEKVIT)/usr/lib
LIBDIRS	+=	$(DEKVIT)/usr/include
